services:
  # arangodb:
  #   image: arangodb:3.12.2
  #   environment:
  #     ARANGO_ROOT_PASSWORD: rootpassword
  #     ARANGO_NO_AUTH: 1
  #   ports:
  #     - 8529:8529
  #   volumes:
  #     - ./arangodb/arangodb3:/var/lib/arangodb3
  #     - ./arangodb/arangodb3-apps:/var/lib/arangodb3-apps
  lab:
    build:
      context: lab/.
    restart: "no"
    ports:
      - 8889:8888
    volumes:
      - ./lab/src:/home/jovyan
    command: start-notebook.py --NotebookApp.token='lab1'
# volumes:
#   arangodb:
#   arangodb_apps:
